<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Sparkles</RootNamespace>
    <AssemblyName>Sparkles</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests/**" />
    <Compile Remove="Git/**" />
    <None Include="InstallationInfo.Directory.cs.in" />
  </ItemGroup>

</Project>
